version: "3.7"

services:
    nginx:
        image: nginx
        container_name: nginx
        volumes:
            - ./docker/nginx/api.conf:/etc/nginx/conf.d/default.conf
            - ./public:/application/public:cached
        ports:
            - 80:80
    php:
        build: .
        container_name: php
        working_dir: /application
        environment:
            PHP_IDE_CONFIG: 'serverName=api'
    mongo:
        image: mongo:latest
        container_name: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: secret
            MONGO_INITDB_DATABASE: articles
        ports:
            - 27017:27017
        volumes:
            - ./docker/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

    inflections:
        build: ./docker/inflections
        depends_on:
            -   mongo
